### ISSUE TITLE
Offer still available?

### ISSUE THREAD

**Issue by TOPAiiN** [exercism/hiring-frontend-developer#14]
Hi folks, just saw the open position but in the description you mentioned that you were keen to make offers by the end of April. Hopefully, there is still a chance to apply.
I thought this was the quickest way to have an answer. Sorry if it is not the appropriate channel.
Thanks in advance.

**Comment by ErikSchierboom** [comment]
The position _is_ still open, yes.

**Comment by TOPAiiN** [comment]
Thanks for the answer, @ErikSchierboom. Will start working on it.
