### ISSUE TITLE
Inquiry regarding Front-end Developer position.

### ISSUE THREAD

**Issue by samyukthasudhakar** [exercism/hiring-frontend-developer#54]
Hi Team. Hope you are having a great week !
I'm looking forward to apply for the front-end dev role. I saw a mention of making the final decision by April in the job advert. Would love to apply if the position is still open. Hope to get in touch soon. Thank you :D

**Comment by iHiD** [comment]
Hey @samyukthasudhakar - so sorry this got missed. Yeah, the job was filled. But I'd love you to apply when we hire for the next front end role in the future!
