### ISSUE TITLE
Mentor Description

### ISSUE THREAD

**Issue by enigmaticmahesh** [exercism/hiring-frontend-developer#7]
For each testimonial in the table, there is a topic on which the testimonial has been given for the mentor. I am unable to get that dat from the api. In the api for each mentor, only 2 data are coming, **handle** and **avatar_url** but not the topic data. Is it required or not? As per figma, I guess it should.

**Comment by ErikSchierboom** [comment]
What specifically do you mean by "topic"?

**Comment by enigmaticmahesh** [comment]
[Image](https://ik.imagekit.io/eclaygb3yqo/Screenshot_2022-03-14_at_5.03.02_PM_HxA_LgM1H.png?ik-sdk-version=javascript-1.4.3&updatedAt=1647257602536)

I am talking about the **On series in bash** text in the image. It is not available in the object in **results** array

**Comment by ErikSchierboom** [comment]
Oh but it is. Series is `exercise.slug`, and `bash` is `track.slug`.

**Comment by enigmaticmahesh** [comment]
Yes, got it. One more thing need to ask, do I have to show 20 testimonials per page ? As, there is 10 testimonials per page in figma. Or am I asking too much and use 20 per page only ?

**Comment by ErikSchierboom** [comment]
You should show all data in the `testimonials.results` array. There is a `pagination` property to help with pagination.
